{"uuid": "aa7583b6-5a5f-4c9f-964a-97e70b87ab9a", "children": ["6fb5c89f-63a9-49fd-b43d-91200417215a"], "befores": [{"name": "excel_results", "status": "passed", "start": 1707287469824, "stop": 1707287469824}], "afters": [{"name": "excel_results::fin", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 13] Permission denied: 'test_results.xlsx'\n", "trace": "  File \"C:\\Users\\admin\\PycharmProjects\\Appium\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\PycharmProjects\\Appium\\account.py\", line 19, in fin\n    wb.save(\"test_results.xlsx\")\n  File \"C:\\Users\\admin\\PycharmProjects\\Appium\\venv\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n    save_workbook(self, filename)\n  File \"C:\\Users\\admin\\PycharmProjects\\Appium\\venv\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\zipfile.py\", line 1281, in __init__\n    self.fp = io.open(file, filemode)\n              ^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1707287486814, "stop": 1707287486816}], "start": 1707287469824, "stop": 1707287486816}