{"uuid": "4ef1816f-500a-4b52-89d9-5594e3798cf6", "children": ["51778b51-0aaa-463b-82ce-5137c4f3e926"], "befores": [{"name": "excel_results", "status": "passed", "start": 1707287758244, "stop": 1707287758244}], "afters": [{"name": "excel_results::fin", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 13] Permission denied: 'test_results.xlsx'\n", "trace": "  File \"C:\\Users\\admin\\PycharmProjects\\Appium\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\PycharmProjects\\Appium\\account.py\", line 19, in fin\n    wb.save(\"test_results.xlsx\")\n  File \"C:\\Users\\admin\\PycharmProjects\\Appium\\venv\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n    save_workbook(self, filename)\n  File \"C:\\Users\\admin\\PycharmProjects\\Appium\\venv\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\zipfile.py\", line 1281, in __init__\n    self.fp = io.open(file, filemode)\n              ^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1707287775453, "stop": 1707287775456}], "start": 1707287758244, "stop": 1707287775456}